language: node_js
node_js:
- '10'

script:
- echo "skipping tests"

before_install:
- cd massage-booking-system-frontend
- npm install
- CI=false npm run build
install: true
install:
- mv build ../massage-booking-system-backend
- cd ../massage-booking-system-backend
- npm install
